- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/loyalty/MLBusinessLoyaltyHeaderView.java
Soluciona NPE ocasionado por el uso de un layout incorrecto en el header de loyalty
> Fix loyalty header NPE

- mlbusinesscomponents/src/main/res/layout/ml_view_business_info.xml
Se fixea el fontsize para la info view
> Info view visual fix

- mlbusinesscomponents/src/main/res/layout/ml_view_business_loyalty_header.xml
Se hacen algunas correcciones visuales sobre el layout de LoyaltyHeader.
> Header Loyalty Ring Refactor Correction

- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/common/downloadapp/MLBusinessDownloadAppView.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/discount/MLBusinessDiscountBoxView.java
Se agrega mejor soporte para los métodos `update` en las vistas. Ahora se soporta el resetteo de onClickListener
> Add better updateView support

- CHANGELOG.md
- README.md
- gradle.properties
> [ci deploy]

- CHANGELOG.md
- mlbusinesscomponents/src/main/res/layout/ml_view_discount_box.xml
Font size was changed in the discount box component.
> Font size updated

- mlbusinesscomponents/src/main/res/layout/ml_view_download.xml
Necesitamos ajustar algunos detalles de UI, como fonts o márgenes.
> [WIP][Loyalty] Pequeños ajustes UI

- CHANGELOG.md
- gradle.properties
Se actualiza el Changelog y el número de versión.
> Changelog and libVersion update for 1.0.7

- CHANGELOG.md
- gradle.properties
- mlbusinesscomponents/build.gradle
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/common/MLBusinessInfoView.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/crossselling/MLBusinessCrossSellingBoxView.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/discount/MLBusinessDiscountBoxAdapter.java
* Migration to UI 8+
* Migration to min api 19
> Using picasso disk cache

- CHANGELOG.md
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/discount/MLBusinessDiscountBoxAdapter.java
- mlbusinesscomponents/src/main/res/drawable/box_icon_overlay.xml
- mlbusinesscomponents/src/main/res/layout/ml_view_discount_box.xml
- mlbusinesscomponents/src/main/res/values/color.xml
Se agrega un overlay sobre las imagenes
> Add overlay on box image

- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/explodingbutton/ButtonProgress.java
- mlbusinesscomponents/src/main/res/drawable-mdpi/button_background.xml
- mlbusinesscomponents/src/main/res/values/color.xml
Change color of background and progress button.
> Change color of button.

- CHANGELOG.md
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/common/MLBusinessSingleItem.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/discount/MLBusinessDiscountBoxAdapter.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/discount/MLBusinessDiscountBoxData.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/discount/MLBusinessDiscountBoxView.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/discount/MLBusinessDiscountTracker.java
- Se agrega un tracker al componente de descuentos
> Add tracker on discount component

- CHANGELOG.md
- app/src/main/java/com/mercadolibre/android/mlbusinesscomponentsapp/ButtonsActivity.java
- app/src/main/res/layout/activity_botones.xml
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/explodingbutton/ButtonProgress.java
- mlbusinesscomponents/src/main/res/layout/view_color_options.xml
- mlbusinesscomponents/src/main/res/values/dimen.xml
Se realiza un refactor del Exploting Button
> Change height exploting button

- CHANGELOG.md
- app/src/main/java/com/mercadolibre/android/mlbusinesscomponentsapp/ButtonsActivity.java
- app/src/main/res/layout/activity_botones.xml
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/explodingbutton/ButtonProgress.java
Se hace refactor en ButtonProgress según tamaño de status bar del dispositivo.
> Refactor in ButtonProgress according to status bar

- CHANGELOG.md
- gradle.properties
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/domain/model/carousel/CarouselCard.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/domain/model/carousel/CarouselPill.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/domain/model/grid/GridItem.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/carousel/CarouselView.java
- Se arregla el decorator del carousel
> Fix carousel

- CHANGELOG.md
- app/src/main/res/raw/touchpoint_carousel.json
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/domain/model/carousel/Carousel.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/domain/model/carousel/CarouselCard.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/domain/model/carousel/CarouselTextFormat.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/domain/model/carousel/LogoImageFormat.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/carousel/CarouselAdapter.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/carousel/CarouselView.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/carousel/HeightCalculatorDelegate.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/carousel/card/CarouselCardPresenter.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/carousel/card/CarouselCardView.java
- mlbusinesscomponents/src/main/res/layout/touchpoint_carousel_card_view.xml
- mlbusinesscomponents/src/main/res/values/styles.xml
* REFACTOR - Add category card to carousel
* REFACTOR - Changing Carousel card layout
> Adding category card to carousel

- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/domain/model/carousel/CarouselCard.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/AbstractTouchpointChildView.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/MLBusinessTouchpointView.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/carousel/CarouselView.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/grid/GridView.java
- mlbusinesscomponents/src/main/res/layout/touchpoint_carousel_card_view.xml
- mlbusinesscomponents/src/main/res/values/dimen.xml
- Se agregaq una altura fija a las subviews para fixear el bug en los huawei
> Add static height

- CHANGELOG.md
- app/src/main/java/com/mercadolibre/android/mlbusinesscomponentsapp/MLBusinessLoyaltyRingDataSample.java
- gradle.properties
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/loyalty/MLBusinessLoyaltyRingCompleteData.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/loyalty/MLBusinessLoyaltyRingData.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/loyalty/MLBusinessLoyaltyRingView.java
- mlbusinesscomponents/src/main/res/layout/ml_view_business_loyalty_ring.xml
Se modifica el componente de Loyalty Ring agregando la posibilidad de tener un subtitulo en el mismo y manteniendo el estado actual en el caso contrario. También se agrega la posibilidad de combinar el estado actual (solo con link) y además tener en cuenta el subtitulo.
EXPERIMENTAL-1.4.0-26052020112532687
**Caso actual:**
**Subtitulo agregado:**
**Subtitulo y link:**
> Loyalty Ring with subtitle

- app/build.gradle
- build.gradle
- gradle.properties
Se arregla el build variant de release
> [Fix] Release build variant

- CHANGELOG.md
- README.md
Update mlbusiness-components to 1.4.0
> [Release] Update to 1.4.0

- CHANGELOG.md
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/domain/model/carousel/CarouselCard.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/carousel/card/CarouselCardView.java
- mlbusinesscomponents/src/main/res/layout/touchpoint_carousel_card_view.xml
* FEATURE - Se modifica el largo del titulo y subtitulo de las cards del carrusel
> fixing title and subtitle max length

- CHANGELOG.md
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/domain/model/carousel/CarouselCard.java
> se mejora el tamaño de las cards de carrusel

- CHANGELOG.md
- gradle.properties
> Feature/mergeback 1.6.1

- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/actioncard/MLBusinessActionCardView.kt
Se agrega efecto ripple a ActionCardView
- [N/A] Chequeado con el equipo de central de descuentos (Obligatorio)
> [Enhancement] Add ripple effect to ActionCardView

- app/build.gradle
- app/src/main/java/com/mercadolibre/android/mlbusinesscomponentsapp/MLBusinessActionCardViewDataSample.kt
- mlbusinesscomponents/src/main/res/layout/ml_view_action_card.xml
Se mejora el lineHeight del componente `MLBusinessActionCardView`
> [Improvement] improvement card action view

- CHANGELOG.md
- app/src/main/res/raw/touchpoint_carousel.json
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/callback/OnClickCallback.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/domain/model/carousel/CarouselCard.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/carousel/card/CarouselCardView.java
- mlbusinesscomponents/src/main/res/layout/touchpoint_carousel_card_view.xml
* FEATURE - Se modifica la forma en la que se envian los trackeos a la central de descuentos desde la card de carrusel de touchpoint
> Fixing UI and TAP in carousel card

- CHANGELOG.md
- gradle.properties
> [Release] Update version to 1.7.1

- CHANGELOG.md
- gradle.properties
> [Release] version 1.8.0

- CHANGELOG.md
- gradle.properties
> release 1.10.0

- CHANGELOG.md
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/common/Constants.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/domain/model/carousel/Carousel.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/domain/model/carousel/CarouselTextFormat.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/domain/model/carousel/LogoImageFormat.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/domain/model/hybrid_carousel/model/HybridCarouselModel.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/tracking/print/TouchpointTracking.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/carousel/CarouselAdapter.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/carousel/CarouselView.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/carousel/HeightCalculatorDelegate.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/carousel/card/CarouselCardView.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/hybrid_carousel/HybridCarouselAdater.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/hybrid_carousel/HybridCarouselView.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/hybrid_carousel/ItemViewHolder.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/hybrid_carousel/default_card/HybridCarouselDefaultViewHolder.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/hybrid_carousel/default_card/card/HybridCarouselDefaultCardView.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/hybrid_carousel/view_more/HybridCarouselViewMoreViewHolder.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/hybrid_carousel/view_more/card/HybridCarouselViewMoreCardView.java
- mlbusinesscomponents/src/main/res/layout/bottom_right_info_view.xml
- mlbusinesscomponents/src/main/res/layout/touchpoint_carousel_view.xml
- mlbusinesscomponents/src/main/res/layout/touchpoint_hybrid_carousel_default_card_view.xml
- mlbusinesscomponents/src/main/res/layout/touchpoint_hybrid_carousel_view.xml
- Se calcula el alto de los items en base al alto real del item mas alto
> Normalize touchpoint items height

- CHANGELOG.md
- gradle.properties
> releasing business Components

- CHANGELOG.md
- mlbusinesscomponents/src/main/res/layout/touchpoint_row_view.xml
- Se quita el separador de la touchpoint row view.
> removing separator view

- CHANGELOG.md
- gradle.properties
> releasing 1.13.0

- CHANGELOG.md
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/domain/model/hybrid_carousel/response/HybridCarouselCardContainer.java
- se agregar equals a hybrid carousel container
> equals added

- CHANGELOG.md
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/cover_carousel/CoverCardViewPagerAdapter.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/cover_carousel/CoverCarouselView.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/cover_carousel/cover_card/CoverCardView.java
- Reutilizo las vistas creadas cuando se bindea otra lista de cards. Si hay de más las elimino y si no, agrego.
MercadoPago | MercadoLibre | Central de descuentos
---- | ---- | ----
> CoverCarousel Improvement

- app/src/main/res/raw/touchpoint_hybrid_carousel.json
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/pickup/MainDescriptionLabelsText.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/pickup/PickUpPresenter.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/pickup/PickUpView.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/row/TouchpointRowPresenter.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/row/TouchpointRowView.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/row/model/TouchpointRowItemInterface.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/row/model/test/TouchpointRowItem.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/domain/model/cover_carousel/model/cover_card/CoverCardContentInterfaceModel.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/domain/model/cover_carousel/model/test/CoverCardContent.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/domain/model/hybrid_carousel/model/default_card/HybridCarouselDefaultCard.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/cover_carousel/cover_card/CoverCardInterfaceView.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/cover_carousel/cover_card/CoverCardPresenter.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/cover_carousel/cover_card/CoverCardView.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/hybrid_carousel/default_card/card/HybridCarouselDefaultCardPresenter.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/hybrid_carousel/default_card/card/HybridCarouselDefaultCardView.java
- mlbusinesscomponents/src/main/res/layout/touchpoint_hybrid_carousel_default_card_view.xml
- mlbusinesscomponents/src/main/res/layout/touchpoint_row_view.xml
> Store state

- CHANGELOG.md
- gradle.properties
> Release 1.17.0

- CHANGELOG.md
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/row/TouchpointRowView.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/row/model/test/TouchpointRowItem.java
- mlbusinesscomponents/src/main/res/layout/touchpoint_row_view.xml
- Se fixea el marge inferiro de hybird row
> Fix row margin bottom

- CHANGELOG.md
- gradle.properties
> Release 1.17.1

- CHANGELOG.md
- mlbusinesscomponents/src/main/res/layout/touchpoint_carousel_view.xml
- mlbusinesscomponents/src/main/res/layout/touchpoint_hybrid_carousel_view.xml
Se apaga el nestedScroll para evitar problemas con el coordinator layout
> fix coordinator layout issues

- CHANGELOG.md
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/hybrid_carousel/default_card/card/HybridCarouselDefaultCardPresenter.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/view/hybrid_carousel/default_card/card/HybridCarouselDefaultCardView.java
- Se fixe logica image top status
> fix Image status

- CHANGELOG.md
- gradle.properties
> Release 1.18.1

- CHANGELOG.md
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/row/TouchpointRowView.java
- mlbusinesscomponents/src/main/res/layout/touchpoint_row_view.xml
- Se fixean las constraints de pickup en hybrid row
> Fix Hybrid row pickup constraints

- CHANGELOG.md
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/row/TouchpointRowPresenter.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/row/TouchpointRowView.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/row/model/TouchpointRowItemInterface.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/row/model/test/TouchpointRowItem.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/domain/model/cover_carousel/model/test/CoverCardContent.java
- mlbusinesscomponents/src/main/res/values/color.xml
- Se agrega soporte a status closed en el title y subtitle de TouchPointRow.
**Antes**
**Después**
> Added closed title and subtitle color

- CHANGELOG.md
- gradle.properties
> Mergeback  v1.20.0.

- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/row/model/TouchpointRowItemInterface.java
> fixed default method

- CHANGELOG.md
- gradle.properties
> Mergeback v1.20.1

- CHANGELOG.md
- gradle.properties
> [Mergeback] Release 1.21.0

- CHANGELOG.md
- gradle.properties
> Release 1.22.0

- CHANGELOG.md
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/row/TouchpointRowPresenter.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/row/TouchpointRowView.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/row/model/MainTitleTopInterface.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/row/model/TouchpointRowItemInterface.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/row/model/test/MainTitleTopResponse.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/row/model/test/TouchpointRowItem.java
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/touchpoint/domain/model/cover_carousel/model/test/CoverCardContent.java
- mlbusinesscomponents/src/main/res/layout/touchpoint_row_view.xml
- mlbusinesscomponents/src/main/res/values/styles.xml
- Se ajusto la touchpoint row view 
> Adjust on TouchPointRowView

- CHANGELOG.md
- gradle.properties
> Mergeback 1.23.0

- CHANGELOG.md
- gradle.properties
- mlbusinesscomponents/build.gradle
Se migra a api mínimo 21 y target 30.
> [Feature] Migrates to min api 21 and target 30

- CHANGELOG.md
- gradle.properties
> Mergeback 2.1.0

- CHANGELOG.md
- mlbusinesscomponents/src/main/java/com/mercadolibre/android/mlbusinesscomponents/components/row/TouchpointRowView.java
Se corrige el solapamiento de vistas en la Row del CoverCarousel
Bug|Fix
--|--
Quien crea el PR, es el responsable de regresionar los modulos afectados
> Fix cover carousel row view

- CHANGELOG.md
- gradle.properties
Bump Kotlin 1.5. 
MDS: [MP + Proximity [Bump Kotlin 1.5 (touchpoint, discovery, review & mlbusiness)]](https://mobile.mercadolibre.com/mobile/store/landing/applications/com.mercadopago.wallet.mds.custom.proximity/builds/18112)
.|.
---|---
<video src="https://user-images.githubusercontent.com/65614580/148987858-79e3456b-29bf-49a7-8970-ab95c5a63459.mp4">|<video src="https://user-images.githubusercontent.com/65614580/148987993-a0c18e21-2e09-4353-9d2c-8d70b2132bd5.mp4">
> Bump Kotlin

- CHANGELOG.md
- gradle.properties
> Mergeback 2.2.0

- CHANGELOG.md
- gradle.properties
Reverts mercadolibre/mlbusiness-components-android#154
> Revert "Bump Kotlin"

- gradle.properties
> Mergeback 2.2.1

- CHANGELOG.md
- gradle.properties
> Mergeback 2.5.0

- CHANGELOG.md
- app/src/main/java/com/mercadolibre/android/mlbusinesscomponentsapp/touchpoint/TouchpointSamples.java
- app/src/main/res/raw/touchpoint_carousel_touchpoint_v2.json
- gradle.properties
- mlbusinesscomponents/src/main/res/layout/touchpoint_carousel_card_full_view_container.xml
Se actualiza el container de la Card Full View y el espaciado entre cards.
> Update Container Card Full View

- CHANGELOG.md
- gradle.properties
> Mergeback 2.7.0
